spring.application.name=customer-service
server.port=0
spring.cloud.config.enabled=false
spring.cloud.discovery.enabled=false
global.params.p1=1
global.params.p2=2
customer.params.x=10
customer.params.y=20
