global.params.p1=333
global.params.p2=3333
spring.h2.console.enabled=true
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
management.endpoints.web.exposure.include=*
management.metrics.export.prometheus.enabled=true
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true

# Forcer la génération des buckets pour le p99
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.minimum-expected-value.http.server.requests=1ms
management.metrics.distribution.maximum-expected-value.http.server.requests=10s
# Activer explicitement les observations
management.observations.key-values.repository.enabled=true